In [1]:
# !pip install flask pandas python-dotenv openpyxl supabase
# !pip install supabase

In [2]:
# pip show supabase

In [13]:
import pandas as pd
import glob
import os
import io

In [22]:
ActivationDetailReport = pd.read_csv(r"D:\i\uploads\raw\ActivationDetailReport_7GF0SCN8M.csv",
    encoding="latin1")
CallidusReport = pd.read_csv(r"D:\i\uploads\raw\CallidusDetail_7GF0T17DL.csv",
    encoding="latin1")
CurCallidusReport = pd.read_csv(r"D:\i\uploads\raw\curCallidus_7GF0SU2WW.csv",
    encoding="latin1")

In [ ]:
# CurCallidusReport.head()

,marketid,custno,username,name,lastname,periodname,dealerpositionname,dealerfullname,dealerregionname,dealeraddress,...,rma,originalsoc,compsoc,compmrc,custno1,fk_store,tradeindeducted,periodnamedate,callidusid,failedaudit
0,METRO-NY,C-70812973,BWH13560,Saurav,Prajapati,April 2026,8603383-NYC,The Portables Choice Group Llc,NaN,NaN,...,NaN,35GBNP,35GBNP,35.0,C-70812973,17433,NaN,2026-04-01,7821635573,NaN
1,METRO-NY,C-70812973,CGN92584,Carol,Aguayo,April 2026,8603383-NYC,The Portables Choice Group Llc,NaN,NaN,...,NaN,BFLX60,BFLX60,65.0,C-70812973,17433,NaN,2026-04-01,7821801635,NaN
2,METRO-NY,C-70812973,BWH13560,Saurav,Prajapati,April 2026,8603383-NYC,The Portables Choice Group Llc,NaN,NaN,...,NaN,TAB20SD,TAB20SD,20.0,C-70812973,17433,NaN,2026-04-01,7821949583,NaN
3,METRO-NY,C-70812973,BWH13560,Saurav,Prajapati,April 2026,8603383-NYC,The Portables Choice Group Llc,NaN,NaN,...,NaN,TAB20SD,TAB20SD,20.0,C-70812973,17433,NaN,2026-04-01,7823340408,NaN
4,METRO-NY,C-70812973,CGN92584,Carol,Aguayo,April 2026,8603383-NYC,The Portables Choice Group Llc,NaN,NaN,...,NaN,40L1WEB,40L1WEB,20.0,C-70812973,17433,NaN,2026-04-01,7823348679,NaN

In [19]:
CurCallidusReport.to_csv(
    r"D:\i\metro\curCallidus_7GF0SU2WW.csv"
)

In [ ]:
storeid	company	serial	acttype	plancode	plantype1	Compensation	Rebate	Chargeback	Post Date

In [23]:
# Collecting columns into new D_FMT

collecting_columns = ActivationDetailReport[['storeid','company','serial','accounttype','plancode','plantype1',]]

In [26]:
collecting_columns.head()

,storeid,company,serial,accounttype,plancode,plantype1
0,C-70812973,DKS WIRELESS 2128007-DCWP,'356795671974397,Prime,35GBNP,Voice
1,C-70812973,DKS WIRELESS 2128007-DCWP,'356795671974397,Prime,SCURE5S,Feature
2,C-70812973,DKS WIRELESS 2128007-DCWP,'016759005739068,Prime,TAB20SD,Voice
3,C-70812973,DKS WIRELESS 2128007-DCWP,'016759005737708,Prime,TAB20SD,Voice
4,C-70812973,DKS WIRELESS 2128007-DCWP,'864644063338388,Prime,HINTFOR,Voice

In [27]:
# collecting_columns = collecting_columns.merge(
#     df3[['id', 'salary', 'department']],
#     on='serial',
#     how='left'
# )